version: '2'

services:
  website:
    build: .
    command: uwsgi --py-autoreload=10 --ini deploy/uwsgi_config.ini
    links:
      - db
    env_file:
      - '.env'
    ports:
      - '8000:8000'
    volumes:
      - ./:/Photos-Docker-Flask

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: insta_admin
      MYSQL_PASSWORD: insta2018
      MYSQL_DATABASE: insta_db

